#!/bin/sh
#
# Copyright (C) 2010 Yann Pouillon
#
# This file is part of the AtomPAW software package. For license information,
# please see the COPYING file in the top-level directory of the source
# distribution.
#

#
# IMPORTANT NOTE:
#
#   For maintainer use only!
#
#   PLEASE DO NOT EDIT THIS FILE, AS IT COULD CAUSE A SERIOUS LOSS OF DATA.
#   *** YOU HAVE BEEN WARNED! ***
#

# Check that we are in the right directory
if test ! -s "./configure.ac" -o ! -s "src/atompaw_prog.F90"; then
  echo "wipeout: Cowardly refusing to remove something from here!"
  exit 1
fi

# Remove temporary directories and files
echo "Removing temporary directories and files..."
rm -rf tmp*
find . -depth -name 'tmp-*' -exec rm -rf {} \;
find src -name '*.~[0-9]~' -exec rm -f {} \;
echo "done."

# Remove autotools files
echo "Removing autotools files..."
find src -depth -name '.deps' -exec rm -rf {} \;
find src -depth -name '.libs' -exec rm -rf {} \;
rm -f core config.log config.status stamp-h1 config.h config.h.in*
rm -rf aclocal.m4 autom4te.cache configure confstat*
(cd config/gnu && rm -f config.guess config.sub depcomp install-sh ltmain.sh missing)
(cd config/m4 && rm -f libtool.m4 ltoptions.m4 ltsugar.m4 ltversion.m4 lt~obsolete.m4)
echo "done."

# Remove Makefiles and machine-generated files
echo "Removing files produced by the configure script..."
rm -f libtool
find . -name Makefile -exec rm {} \;
find . -name Makefile.in -exec rm {} \;
rm -f src/pkginfo.f90
echo "done."

# Remove object files, libraries and programs
echo "Removing object files, libraries and programs..."
rm -f src/atompaw
rm -f src/graphatom
rm -f src/libxc_id.in
find src -name '*.la' -o -name '*.lo' -exec rm {} \;
find src -name '*.a' -o -name '*.o' -exec rm {} \;
find src -name '*.mod' -exec rm {} \;
echo "done."

# Remove distribution files
echo "Removing distribution files..."
chmod -Rf u+w atompaw-[0-9].[0-9].[0-9]*
rm -rf atompaw-[0-9].[0-9].[0-9]*
echo "done."
