#!/bin/csh -f
'rm' -f wfn.gnu
set fl=wfn$1
echo $fl
set fl='"'$fl'"'
echo $fl
echo 'plot' $fl 'using 1:2 with lines,' $fl 'using 1:3 with lines,' $fl 'using 1:4 with lines, 0' >wfn.gnu
echo ' ' >>wfn.gnu
echo 'pause -1 "******Press return to continue******"' >> wfn.gnu
gnuplot wfn.gnu
